"""push

Revision ID: 04c070dbc8a8
Revises: 
Create Date: 2026-09-23 19:05:01.896921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04c070dbc8a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=128), nullable=False),
    sa.Column('execution_mode', sa.String(length=24), nullable=False),
    sa.Column('risk_preset', sa.String(length=24), nullable=False),
    sa.Column('max_trade_amount', sa.Float(), nullable=False),
    sa.Column('authorized_admin_telegram_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('telegram_bot_token', sa.String(length=256), nullable=True),
    sa.Column('polymarket_api_key', sa.String(length=256), nullable=True),
    sa.Column('polymarket_api_secret', sa.Text(), nullable=True),
    sa.Column('polymarket_passphrase', sa.String(length=256), nullable=True),
    sa.Column('wallet_private_key', sa.Text(), nullable=True),
    sa.Column('admin_security_pin', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_settings_id'), 'institutional_settings', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('bankroll', sa.Float(), nullable=False),
    sa.Column('risk_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('sports_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('league', sa.String(length=64), nullable=False),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=160), nullable=True),
    sa.Column('weather', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('home_team_id', sa.String(length=64), nullable=True),
    sa.Column('away_team_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_sports_events_away_team_id'), 'sports_events', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_sports_events_home_team_id'), 'sports_events', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_sports_events_id'), 'sports_events', ['id'], unique=False)
    op.create_index(op.f('ix_sports_events_sport'), 'sports_events', ['sport'], unique=False)
    op.create_index(op.f('ix_sports_events_start_time'), 'sports_events', ['start_time'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('league', sa.String(length=64), nullable=False),
    sa.Column('abbreviation', sa.String(length=16), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_league'), 'teams', ['league'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_sport'), 'teams', ['sport'], unique=False)
    op.create_table('telegram_auth_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('challenge_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('pending_trade', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_hash')
    )
    op.create_index(op.f('ix_telegram_auth_challenges_expires_at'), 'telegram_auth_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_auth_challenges_id'), 'telegram_auth_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_auth_challenges_telegram_user_id'), 'telegram_auth_challenges', ['telegram_user_id'], unique=False)
    op.create_table('trade_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('condition_id', sa.String(length=256), nullable=True),
    sa.Column('token_id', sa.String(length=256), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('external_order_id', sa.String(length=256), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('guardrail_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_order_id')
    )
    op.create_index(op.f('ix_trade_executions_id'), 'trade_executions', ['id'], unique=False)
    op.create_index(op.f('ix_trade_executions_provider'), 'trade_executions', ['provider'], unique=False)
    op.create_index(op.f('ix_trade_executions_status'), 'trade_executions', ['status'], unique=False)
    op.create_table('injury_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('player', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('impact_points', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=96), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sports_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_reports_event_id'), 'injury_reports', ['event_id'], unique=False)
    op.create_index(op.f('ix_injury_reports_id'), 'injury_reports', ['id'], unique=False)
    op.create_table('market_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=128), nullable=False),
    sa.Column('american_odds', sa.Integer(), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_type', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('contract_id', sa.String(length=128), nullable=True),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('no_price', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('order_book', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opening_american_odds', sa.Integer(), nullable=True),
    sa.Column('closing_american_odds', sa.Integer(), nullable=True),
    sa.Column('is_closing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['sports_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_quotes_captured_at'), 'market_quotes', ['captured_at'], unique=False)
    op.create_index(op.f('ix_market_quotes_event_id'), 'market_quotes', ['event_id'], unique=False)
    op.create_index(op.f('ix_market_quotes_id'), 'market_quotes', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=128), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sports_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_event_id'), 'positions', ['event_id'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_table('prediction_market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('question', sa.String(length=240), nullable=False),
    sa.Column('outcome', sa.String(length=128), nullable=False),
    sa.Column('share_price_cents', sa.Float(), nullable=False),
    sa.Column('bid_cents', sa.Float(), nullable=True),
    sa.Column('ask_cents', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('order_book', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deep_link', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sports_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_market_snapshots_captured_at'), 'prediction_market_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_prediction_market_snapshots_event_id'), 'prediction_market_snapshots', ['event_id'], unique=False)
    op.create_index(op.f('ix_prediction_market_snapshots_id'), 'prediction_market_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_market_snapshots_market_id'), 'prediction_market_snapshots', ['market_id'], unique=False)
    op.create_index(op.f('ix_prediction_market_snapshots_provider'), 'prediction_market_snapshots', ['provider'], unique=False)
    op.create_table('signal_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sports_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_alerts_event_id'), 'signal_alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_signal_alerts_id'), 'signal_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_alerts_id'), table_name='signal_alerts')
    op.drop_index(op.f('ix_signal_alerts_event_id'), table_name='signal_alerts')
    op.drop_table('signal_alerts')
    op.drop_index(op.f('ix_prediction_market_snapshots_provider'), table_name='prediction_market_snapshots')
    op.drop_index(op.f('ix_prediction_market_snapshots_market_id'), table_name='prediction_market_snapshots')
    op.drop_index(op.f('ix_prediction_market_snapshots_id'), table_name='prediction_market_snapshots')
    op.drop_index(op.f('ix_prediction_market_snapshots_event_id'), table_name='prediction_market_snapshots')
    op.drop_index(op.f('ix_prediction_market_snapshots_captured_at'), table_name='prediction_market_snapshots')
    op.drop_table('prediction_market_snapshots')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_event_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_market_quotes_id'), table_name='market_quotes')
    op.drop_index(op.f('ix_market_quotes_event_id'), table_name='market_quotes')
    op.drop_index(op.f('ix_market_quotes_captured_at'), table_name='market_quotes')
    op.drop_table('market_quotes')
    op.drop_index(op.f('ix_injury_reports_id'), table_name='injury_reports')
    op.drop_index(op.f('ix_injury_reports_event_id'), table_name='injury_reports')
    op.drop_table('injury_reports')
    op.drop_index(op.f('ix_trade_executions_status'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_provider'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_id'), table_name='trade_executions')
    op.drop_table('trade_executions')
    op.drop_index(op.f('ix_telegram_auth_challenges_telegram_user_id'), table_name='telegram_auth_challenges')
    op.drop_index(op.f('ix_telegram_auth_challenges_id'), table_name='telegram_auth_challenges')
    op.drop_index(op.f('ix_telegram_auth_challenges_expires_at'), table_name='telegram_auth_challenges')
    op.drop_table('telegram_auth_challenges')
    op.drop_index(op.f('ix_teams_sport'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_league'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sports_events_start_time'), table_name='sports_events')
    op.drop_index(op.f('ix_sports_events_sport'), table_name='sports_events')
    op.drop_index(op.f('ix_sports_events_id'), table_name='sports_events')
    op.drop_index(op.f('ix_sports_events_home_team_id'), table_name='sports_events')
    op.drop_index(op.f('ix_sports_events_away_team_id'), table_name='sports_events')
    op.drop_table('sports_events')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_institutional_settings_id'), table_name='institutional_settings')
    op.drop_table('institutional_settings')
    # ### end Alembic commands ###
